#
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: batch/v1
kind: Job
metadata:
  name: job-worker-infer
spec:
  parallelism: 77
  backoffLimit: 10000
  template:
    metadata:
      name: job-worker-infer
      annotations:
        tf-version.cloud-tpus.google.com: "nightly"
    spec:
      containers:
      - name: c
        image: gcr.io/bert-annotator-xgcp/job-worker-infer
        command:
        - bash
        - -c
        - |
          python worker_infer.py $(KUBE_GOOGLE_CLOUD_TPU_ENDPOINTS)
        ports:
        - containerPort: 80
          hostIP: 10.0.0.1
          hostPort: 8080
        resources:
          limits:
            cloud-tpus.google.com/preemptible-v2: 8

      restartPolicy: OnFailure
