apiVersion: batch/v1
kind: Job
metadata:
  name: job-new-tasks
spec:
  parallelism: 1
  template:
    metadata:
      name: job-new-tasks
    spec:
      containers:
      - name: c
        image: gcr.io/bert-annotator-xgcp/job-new-tasks
      restartPolicy: OnFailure
